# docker-compose.yml
version: '3.5'

services:
    jupyter:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
            - "10000:8888"
            - "8787:8787" 
            - "8786:8786"
        volumes:
          - "./src:/opt/kpi_lte"

